console.log("script start")

setTimeout(()=>{
    console.log("inside settimeout")
},0.1)

console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")
console.log("script end")